### ISSUE TITLE
вопрос по монге

### ISSUE THREAD

**Issue by ArturKalmus** [mailgva/Budget#10]
совет -> в репозитории JoinRequestRepository есть метод findById - его можно упростить до 1 строки
       return mongoRepository.findById(id, JoinRequest.class);

Подскажите, плиз, почему в этом же методе, как и во всех остальных Вы используете в запросах к монге  "id", а не "_id"  ?

**Comment by mailgva** [comment]
Добрый день!
Спасибо, попробую, если все будет ок, тогда будет рефакторинг  )

Видимо на тот момент когда все начиналось мне попались именно такие
примеры. Скорей всего монготемплейт сам понимает что id и _id это одно и то
же.

сб, 9 дек. 2023 г., 12:47 ArturKalmus ***@***.***>:

**Comment by mailgva** [comment]
> совет -> в репозитории JoinRequestRepository есть метод findById - его можно упростить до 1 строки return mongoRepository.findById(id, JoinRequest.class);
> 
> Подскажите, плиз, почему в этом же методе, как и во всех остальных Вы используете в запросах к монге "id", а не "_id" ?

Спасибо! Пофикшено!
